version: "3.8"

services:
  wraith:
    build: .
    container_name: wraith-service
    ports:
      - "5678:5678"
    volumes:
      - wraith-data:/data
    restart: unless-stopped
    environment:
      - GNOSIS_WRAITH_STORAGE_PATH=/data
      - QUART_APP=gnosis_wraith.server.app:app
      - QUART_ENV=production
    profiles: [cpu]

  wraith-gpu:
    build: .
    container_name: wraith-service-gpu
    ports:
      - "5678:5678"
    volumes:
      - wraith-data:/data
    restart: unless-stopped
    environment:
      - GNOSIS_WRAITH_STORAGE_PATH=/data
      - QUART_APP=gnosis_wraith.server.app:app
      - QUART_ENV=production
    profiles: [gpu]

volumes:
  wraith-data:
    driver: local