name: gnosis_wraith
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - pillow
  - markdown
  - beautifulsoup4
  - click>=8.0
  - nltk
  - pip:
    - quart>=0.18.0
    - uvicorn>=0.20.0
    - playwright>=1.30.0
    - easyocr>=1.7.0
    - newspaper3k>=0.2.8
    - readability-lxml>=0.8.1